name: Sync with Upstream

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: Sync with Upstream
      run: |
        # Add upstream remote
        git remote add upstream https://github.com/microsoft/vscode.git
        git fetch upstream

        # Check if upstream has new changes
        if git rev-list HEAD..upstream/main --count > 0; then
          # Merge directly into main
          git merge upstream/main
          git push origin main
          echo "Changes from upstream were merged successfully"
        else
          echo "No new changes from upstream"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
